### PR TITLE
played around w heatmaps

### PR DESCRIPTION
**Pull request by chenalison**
image

### CODE REVIEW

**Comment by vtlai88** [comment]
this is looking great!!

**Comment by CesarAyuso** [comment]
Nice job on getting most of this implemented so fast! 

Do you think you can make the tooltip show both DO and Temp so user can see both at a time. (similar to our other charts)

Minor nitpick: I think the DO legend should be inverted to match the pic provided by Alicia
Screen Shot 2022-05-17 at 10 43 42 PM

**Comment by chenalison** [comment]
didn't notice the comments, I've been messing with the colors
image

**Comment by chenalison** [comment]
image

**Comment by chenalison** [comment]
image

**Comment by CesarAyuso** [comment]
This looks good to me! I think the max depth line could be thinner but thats just styling.

**Pull request merged**
