### PR TITLE
started ctd react graph

### PR DESCRIPTION
**Pull request by chenalison**
imageimage
- only for UA-01

### CODE REVIEW

**Comment by chenalison** [comment]
image

**Comment by CesarAyuso** [comment]
Light green color is hard to read for special conductivity.

**Comment by chenalison** [comment]
image

**Comment by chenalison** [comment]
image

**Comment by KennethLieu** [comment]
One point I would like to make is that for some of the visualizations, there is a lot of "noise" that Alicia mentions, and how she would like to see them not included in the visualizations display. Other than that, I think it looks great!

**Comment by vtlai88** [comment]
> 
@KennethLieu 
can you elaborate more on how this can be fixed?

**Comment by vtlai88** [comment]
also, for these sites, we should have a dropdown on the dates that actually have data.

also, on the previous comment, maybe try using a smoother line? @KennethLieu please provide some help on this

**Comment by vtlai88** [comment]
Screen Shot 2022-05-09 at 7 52 03 PM

**Comment by KennethLieu** [comment]
For the noise part, I remember Alicia wants us to simply not include the graph at all in the display. And yes, we should have some dropdown of different dates with data rather than using a calendar. During last week's meeting, she mention she would like to see dropdowns for each the year, the month, and the day. And another dropdown for displaying different sites.

**Comment by chenalison** [comment]
I removed duplicate points. Without duplicate points it looks like
image
but I guess that's not the noise

**Comment by chenalison** [comment]
the issue with UA-06 3/2019 is because it's using data from 3/18 AND 3/19

**Comment by vtlai88** [comment]
yeah, i think the dropdown dates will fix this

**Comment by chenalison** [comment]
image
image

**Comment by CesarAyuso** [comment]
initial dropdown could be sized smaller. "N/A" instead of "No options available". Other than that this lgtm, great work!

**Comment by vtlai88** [comment]
another detail is the hover on the dropdown. the hover blue color doesn't seem to sync up with the selected value. it looks like there's always a blue hover on the first value.
Screen Shot 2022-05-10 at 12 12 51 PM
Screen Shot 2022-05-10 at 12 11 08 PM

**Comment by CesarAyuso** [comment]
Screen Shot 2022-05-10 at 1 25 33 PM
Tooltip should have units.

**Comment by CesarAyuso** [comment]
lgtm!

**Pull request merged**
