### PR TITLE
multiple years works on Met charts

### PR DESCRIPTION
**Pull request by CesarAyuso**
This PR allows users to select multiple years. This was done with multiple fetch calls. I set the max days for the fetch calls to be 150 days. 

This PR also fixes timezone issues. Previously when a user would query for a day it would return the "UTC date". This means there would be an offset and it wouldn't be showing the actual PST date.

### CODE REVIEW

**Comment by vtlai88** [comment]
looking good so far, just some things i noticed
- a bit slow/laggy when getting long period of time --> maybe add a FAQ to disclose this behavior
- EX. when zooming, users might need to wait a bit for the chart to zoom

other than that, looks good so far.

**Comment by CesarAyuso** [comment]
Multiple years works now. For now I commented out the error status. I think its better if we allow users to select multiple years
Screen Shot 2022-05-25 at 2 00 24 PM

**Comment by CesarAyuso** [comment]
Technically the start date still has a UTC offset. You could see it in this example. Kind of a pain to fix. Will leave it as is
Screen Shot 2022-05-25 at 2 06 39 PM

**Comment by vtlai88** [comment]
this looks good!

**Comment by chenalison** [comment]
looks good

**Pull request merged**
