### PR TITLE
met gps update; bek as abbreviation for beakbane island; fixed wind direction for clean data; add wind dir to tooltip

### PR DESCRIPTION
**Pull request by chenalison**

### CODE REVIEW

**Comment by chenalison** [comment]
fixed wind direction for clean data
image

**Comment by chenalison** [comment]
image

**Comment by CesarAyuso** [comment]
When I try to load a date that overlaps with clean and realtime data it only shows the real data. 
Screen Shot 2022-05-17 at 4 07 49 PM

**Comment by vtlai88** [comment]
same thing for me, the last date is 2-4-2022

Screen Shot 2022-05-17 at 11 32 16 AM

**Comment by vtlai88** [comment]
what i noticed was when i put dates from October 2021 to today, the last date shown is 2-4-2022. However, a short time period, say 12-30-2021 to today works fine.

**Comment by vtlai88** [comment]
Screen Shot 2022-05-17 at 4 23 08 PM
this one is a shorter time period

**Comment by vtlai88** [comment]
the graphs lgtm!
one thing: i loaded around 8 months of data and i tried toggling the graphs below. was a bit laggy for me and got unresponsive error pop-up. Maybe someone else can test this?

**Comment by CesarAyuso** [comment]
Regarding the lag with large dates, I think highcharts has this which you could look into: https://www.highcharts.com/docs/advanced-chart-features/boost-module 

One note, can you make the Relative Hum max be 100% and max Temperature could be capped at around 130F

**Pull request merged**
