### PR TITLE
started tchain heatmap in react

### PR DESCRIPTION
**Pull request by chenalison**
image

### CODE REVIEW

**Comment by chenalison** [comment]
image

**Comment by vtlai88** [comment]
feedback:

Screen Shot 2022-05-09 at 8 30 32 PM
the tooltip needs to show date format and add units on the last variable

**Comment by vtlai88** [comment]
looks good, merging this!

**Comment by vtlai88** [comment]
actually, before that, can you resolve this conflict?

**Comment by chenalison** [comment]
I can do that

**Pull request merged**
